server:
  port: 8082

spring:
  profiles :
    active : local
  cloud:
    openfeign :
      okhttp :
        enabled : true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:order-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service

logging :
  pattern :
    level : "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


product-service:
  url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile : docker
  datasource:
    url: jdbc:postgresql://order-postgres:5432/orderdb?schema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
