apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: msa-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
